### ISSUE TITLE
Changing Color in Config?

### ISSUE THREAD

**Issue by benkraw** [jeka-kiselyov/aws-cloudwatch-chart#2]
I was wondering what the proper way to create a config file? I think it would be useful to give an example? For example this does not render multiple colors?

  {
    "metrics": [{
        "title": "Old",
        "namespace": "AWS/EC2",
        "metricName": "CPUUtilization",
        "statisticValues": "Average",
        "unit": "Percent",
        "color": "orange",
        "thickness": 2,
        "dashed": true,
        "InstanceId": "i-378014f0"
    },

{
        "title": "Old2",
        "namespace": "AWS/EC2",
        "metricName": "CPUUtilization",
        "statisticValues": "Average",
        "unit": "Percent",
        "color": "red",
        "thickness": 2,
        "dashed": true,
        "InstanceId": "i-32fdf6e8"
    }

```
],
"aws": {
    "accessKeyId": "XXXXXXX",
    "secretAccessKey": "XXXXXX",
    "region": "us-west-2"
},
"timeOffset": 1000,
"timePeriod": 60,
"chartSamples": 20,
"width": 1000,
"height": 250
```

  }

**Comment by jeka-kiselyov** [comment]
@benkraw it supports RRGGBB format for color only ( https://developers.google.com/chart/image/docs/gallery/line_charts#series-colors-chco )

You can check sample code here: https://gist.github.com/jeka-kiselyov/3f3801a165cab9e4a9fd

 Valid is: "color": "9caff4" or "color": "FF0000".
